site_name: Koros Docs
site_url: https://koros33.github.io
theme:
  name: material

nav:
  nav:
  - Home: index.md
  - About: about.md
  - Product Guides: product guides/index.md
  - API Docs:
      - Overview: api-docs/index.md
      - Weather API: api-docs/weather.md
      - Payments API: api-docs/payments.md
  - Blog: blog/index.md
  - Contact: contact.md
