# Site Information
site_name: Koros docs
site_url: https://koros33.github.io/
site_author: Koros
site_description: Documentation site for Koros33 projects

# Repository
repo_name: koros33/koros33.github.io
repo_url: https://github.com/koros33/koros33.github.io
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Koros33

# Theme Configuration
theme:
  name: material
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
  - tags:
      tags_file: tags.md

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
- Home: index.md
  - About: about.md
  - Product Guides: 
      - Overview: product guides/index.md
  - API Docs:
      - Overview: API docs/index.md
      - Weather API: API docs/weather.md
      - Payments API: API docs/payments.md
  - Blog: blogs/index.md
  - Contact: contact.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/koros33
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/koros33
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/koros33
  analytics:
    provider: google
    property: G-XXXXXXXXXX  # Replace with your Google Analytics ID
  version:
    provider: mike

# Extra CSS/JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
